### ISSUE TITLE
How to install cuda-drivers

### ISSUE THREAD

**Issue by ucerd** [sdsc/cuda-roll#1]
Thanks for the roll
We able to install 10-1 toolkit 

Could you please guide us how to install driver roll.
Currently we are manually installing it.

**Comment by tcooper** [comment]
As per the README.md file this roll simply provides an example of how to capture and bundle the NVIDIA RPMS for CUDA. It does not provide the steps to install. I can say that you will likely need to create graph and node XML files that install scripts to install the required RPMs during first boot after installation. There are multiple conflicts in the NVIDIA RPMs that preclude them from being installed by Anaconda during kickstart. If you take this question to the Rocks Mailing List you will likely find someone who can help. You can sign up for the Rocks Mailing List here... http://www.rocksclusters.org/docs.html
